#!/bin/sh

if [ "$1" = "--mixed" ]; then
  echo '{"message": "JSON message one", "severity": "debug"}'
  echo 'line of plain text output'
  echo '{"message": "JSON message two", "severity": "warning"}'
elif [ "$1" = "--complex" ]; then
  echo '{"message": "server started", "severity": "info", "timestamp": "2017-09-28T05:56:36Z", "port": "8080"}'
  echo '{"message": "templates loaded", "severity": "debug", "timestamp": "2017-09-28T05:56:37Z"}'
  echo '{"message": "request initialized", "severity": "trace", "timestamp": "2017-09-28T06:43:13Z", "user": "john"}'
  echo '{"message": "failed to handle request", "severity": "error", "timestamp": "2017-09-28T06:43:14Z", "error": "no such template"}'
elif [ "$1" = "--no-message" ]; then
  echo '{"message": "", "severity": "trace", "timestamp": "2017-09-28T06:43:13Z", "user": "john"}'
  echo '{"msg": "", "severity": "error", "timestamp": "2017-09-28T06:43:14Z", "@version": "1.0.0"}'
elif [ "$1" = "--nested-message" ]; then
  echo '{"timestamp":"2022-02-15T18:47:10.821422Z","level":"INFO","fields":{"message":"shaving yaks","yaks":7},"target":"fmt_json","spans":{"yaks":7,"name":"shaving_yaks"}}'
  echo '{"timestamp":"2022-02-15T18:47:10.821495Z","level":"TRACE","fields":{"message":"hello! Im gonna shave a yak","excitement":"yay!"},"target":"fmt_json","spans":{"yaks":7,"name":"shaving_yaks"}}'
else
  echo '{"message": "Hello, world!!", "severity": "info"}'
  echo '{"message": "skipping file", "severity": "warn", "file": "empty.txt"}'
fi
