#!/bin/sh
set -e
cd "$(dirname "$0")/.."

command -v cram >/dev/null 2>&1 || {
  echo 'missing test dependency: cram' >&2
  echo 'install using: pip install cram' >&2
}

command -v dep >/dev/null 2>&1 || {
  go get -u github.com/golang/dep/cmd/dep
}
dep ensure
