#!/bin/sh
set -e
cd "$(dirname "$0")/.."

go test ./...

gometalinter --vendor -D errcheck -D gosec ./...

go install
(
  cd examples
  export JL_OPTS="--no-color"
  PATH="${PATH}:$(pwd)/mocks"
  export PATH
  export GOPATH="${TMPDIR:-/tmp}/go"
  cram -E --verbose --indent=4 ../README.md ./*.md
)
