#!/bin/sh
set -e
cd "$(dirname "$0")/.."

go mod verify
go test ./...

"$(go env GOPATH)/bin/golangci-lint" run ./...

go install
(
  cd examples
  export JL_OPTS="--no-color"
  PATH="$(go env GOPATH)/bin:${PATH}:$(pwd)/mocks"
  export PATH
  cram -E --verbose --indent=4 ../README.md ./*.md
)
