name: golang
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - run: go version
      - run: go mod verify
      - run: go test -v ./...
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
